### ISSUE TITLE
Developer's address puts a big burden on client

### ISSUE THREAD

**Issue by erlend-sh** [indieopensource/open-dev-time-block#7]
Hey!

Thanks so much for this plain-english contract, we hope to make good use of it with [Amethyst](https://github.com/amethyst/). We are putting it to the test as we speak, contracting a developer to work on some [winit](https://github.com/rust-windowing/winit/) issues that are blocking a big feature release for us.

In reviewing this contract, my US colleagues deemed it unfeasible to defer to the *Developer's address*.

> some states/counties in the US have REALLY wacky contract laws
> Delaware, for example, has an entire chancery court

We've changed this to *Client's address*, which in our case is Washington. Of course, by doing so we can no longer say we're using standard Open Development Time Block Terms.

Are we missing something here about the importance of *Developer's address* being the only option? Perhaps Developer/client address could be a toggle.

**Comment by kemitchell** [comment]
@erlend-sh clients will likely prefer the governing law of their "home base", while developers will likely prefer the governing law of their own. When the developer proposes the terms, they can provide their address in their signature block. When the client proposes the terms, they can do the same.

FWIW, I would not describe Delaware contract law as wacky. Actually, companies that aren't based anywhere near Delaware, but formed under its popular corporation law, very frequently choose Delaware law to govern their contracts. There is a chancery court in Delaware, but it's actually broadly respected as the most expert and developed court of corporate law in the United States. It just so happens that it has a strange, historic-sounding name.

I would like both clients and developers to be comfortable proposing the form. Perhaps we could add a blank for the governing law to the proposal, and change the terms to choose the developer's "home" law if the proposal doesn't say something different.
